server:
  port: 8030
# 服务名称及为nacos中服务的名称
spring:
  application:
    name: order-ribbon
  cloud:
    nacos:
      server-addr: 192.168.2.60:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public

stock-nacos:
  ribbon:
        # NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
        # 自定义负载均衡策略
        NFLoadBalancerRuleClassName: com.neil.ribbon.rule.CustomRule
ribbon:
  eager-load:
    # 开启ribbon饥饿加载
    enabled: true
    # 配置stock-nacos使用ribbon饥饿加载，多个使用逗号分隔
    clients: stock-nacos

