server:
  port: 8031
# 服务名称及为nacos中服务的名称
spring:
  application:
    name: order-nacos-gs
  cloud:
    nacos:
      server-addr: 192.168.2.60:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    # 禁掉SpringCloud中的ribbon(SpringCloud默认使用ribbon作为负载均衡器)
    loadbalancer:
      ribbon:
        enabled: false